## Note - Oversampling can not be done in binder.  There is not enough compute resources

In [1]:
# Loading the necessary library files
import pandas as pd

In [2]:
# Loading data from the drive

# Please change the filename as per the location where the file is stored
filename = 'https://raw.githubusercontent.com/fenago/nypd/main/data/NYPD_SQF.csv'
# Loading the data using pandas

nypdData = pd.read_csv(filename,sep=",")
nypdData.head()

year  pct sex race  stopped  arrested  frisked  searched  summoned  \
0  2003  1.0   F    A      1.0       0.0      1.0       1.0       0.0   
1  2003  1.0   F    B     11.0       2.0      2.0       0.0       0.0   
2  2003  1.0   F    I      0.0       0.0      0.0       0.0       0.0   
3  2003  1.0   F    P      1.0       0.0      0.0       0.0       0.0   
4  2003  1.0   F    Q      6.0       1.0      1.0       0.0       0.0   

   contrabn  ...  cs_bulge  rf_vcrim  rf_othsw  rf_attir  rf_vcact  rf_rfcmp  \
0       0.0  ...       0.0       0.0       1.0       0.0       0.0       0.0   
1       0.0  ...       0.0       2.0       2.0       0.0       0.0       0.0   
2       0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3       0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4       0.0  ...       0.0       0.0       0.0       1.0       0.0       0.0   

   rf_verbl  rf_knowl  rf_furtv  rf_bulge  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 31 columns]

**Feature engineering steps**

Let us now do some feature engineering to the data. First we will scale the numerical data and then convert the ordinal data to 
dummy data

In [3]:
from sklearn.preprocessing import RobustScaler

rob_scaler = RobustScaler()

# Converting each of the columns to scaled version

nypdData['stoppedScaled'] = rob_scaler.fit_transform(nypdData['stopped'].values.reshape(-1,1))
nypdData['arrestedScaled'] = rob_scaler.fit_transform(nypdData['arrested'].values.reshape(-1,1))
nypdData['friskedScaled'] = rob_scaler.fit_transform(nypdData['frisked'].values.reshape(-1,1))
nypdData['searchedScaled'] = rob_scaler.fit_transform(nypdData['searched'].values.reshape(-1,1))
nypdData['summonedScaled'] = rob_scaler.fit_transform(nypdData['summoned'].values.reshape(-1,1))
nypdData['contrabnScaled'] = rob_scaler.fit_transform(nypdData['contrabn'].values.reshape(-1,1))
nypdData['weapnfndScaled'] = rob_scaler.fit_transform(nypdData['weapnfnd'].values.reshape(-1,1))
nypdData['pf_weapnScaled'] = rob_scaler.fit_transform(nypdData['pf_weapn'].values.reshape(-1,1))
nypdData['pf_hcuffScaled'] = rob_scaler.fit_transform(nypdData['pf_hcuff'].values.reshape(-1,1))
nypdData['cs_objcsScaled'] = rob_scaler.fit_transform(nypdData['cs_objcs'].values.reshape(-1,1))
nypdData['cs_descrScaled'] = rob_scaler.fit_transform(nypdData['cs_descr'].values.reshape(-1,1))
nypdData['cs_casngScaled'] = rob_scaler.fit_transform(nypdData['cs_casng'].values.reshape(-1,1))
nypdData['cs_lkoutScaled'] = rob_scaler.fit_transform(nypdData['cs_lkout'].values.reshape(-1,1))
nypdData['cs_clothScaled'] = rob_scaler.fit_transform(nypdData['cs_cloth'].values.reshape(-1,1))
nypdData['cs_drgtrScaled'] = rob_scaler.fit_transform(nypdData['cs_drgtr'].values.reshape(-1,1))
nypdData['cs_furtvScaled'] = rob_scaler.fit_transform(nypdData['cs_furtv'].values.reshape(-1,1))
nypdData['cs_vcrimScaled'] = rob_scaler.fit_transform(nypdData['cs_vcrim'].values.reshape(-1,1))
nypdData['cs_bulgeScaled'] = rob_scaler.fit_transform(nypdData['cs_bulge'].values.reshape(-1,1))
nypdData['rf_vcrimScaled'] = rob_scaler.fit_transform(nypdData['rf_vcrim'].values.reshape(-1,1))
nypdData['rf_othswScaled'] = rob_scaler.fit_transform(nypdData['rf_othsw'].values.reshape(-1,1))
nypdData['rf_attirScaled'] = rob_scaler.fit_transform(nypdData['rf_attir'].values.reshape(-1,1))
nypdData['rf_vcactScaled'] = rob_scaler.fit_transform(nypdData['rf_vcact'].values.reshape(-1,1))
nypdData['rf_rfcmpScaled'] = rob_scaler.fit_transform(nypdData['rf_rfcmp'].values.reshape(-1,1))
nypdData['rf_verblScaled'] = rob_scaler.fit_transform(nypdData['rf_verbl'].values.reshape(-1,1))
nypdData['rf_knowlScaled'] = rob_scaler.fit_transform(nypdData['rf_knowl'].values.reshape(-1,1))
nypdData['rf_furtvScaled'] = rob_scaler.fit_transform(nypdData['rf_furtv'].values.reshape(-1,1))
nypdData['rf_bulgeScaled'] = rob_scaler.fit_transform(nypdData['rf_bulge'].values.reshape(-1,1))


# Dropping the original columns

nypdData.drop(['year','stopped','arrested','frisked','searched','summoned','contrabn','weapnfnd','pf_weapn','pf_hcuff','cs_objcs','cs_descr','cs_casng','cs_lkout','cs_cloth','cs_drgtr','cs_furtv','cs_vcrim','cs_bulge','rf_othsw','rf_attir','rf_vcact','rf_rfcmp','rf_verbl','rf_knowl','rf_furtv','rf_bulge'],
              axis=1, inplace=True)

# Print the head of the data

nypdData.head()

pct sex race  rf_vcrim  stoppedScaled  arrestedScaled  friskedScaled  \
0  1.0   F    A       0.0      -0.189573         -0.1875      -0.136364   
1  1.0   F    B       2.0      -0.142180         -0.0625      -0.125000   
2  1.0   F    I       0.0      -0.194313         -0.1875      -0.147727   
3  1.0   F    P       0.0      -0.189573         -0.1875      -0.147727   
4  1.0   F    Q       0.0      -0.165877         -0.1250      -0.136364   

   searchedScaled  summonedScaled  contrabnScaled  ...  cs_bulgeScaled  \
0       -0.105263       -0.166667            -0.2  ...       -0.090909   
1       -0.157895       -0.166667            -0.2  ...       -0.090909   
2       -0.157895       -0.166667            -0.2  ...       -0.090909   
3       -0.157895       -0.166667            -0.2  ...       -0.090909   
4       -0.157895       -0.166667            -0.2  ...       -0.090909   

   rf_vcrimScaled  rf_othswScaled  rf_attirScaled  rf_vcactScaled  \
0       -0.111111       -0.066667            -0.1       -0.083333   
1        0.000000        0.000000            -0.1       -0.083333   
2       -0.111111       -0.133333            -0.1       -0.083333   
3       -0.111111       -0.133333            -0.1       -0.083333   
4       -0.111111       -0.133333             0.0       -0.083333   

   rf_rfcmpScaled  rf_verblScaled  rf_knowlScaled  rf_furtvScaled  \
0       -0.133333             0.0             0.0       -0.142857   
1       -0.133333             0.0             0.0       -0.142857   
2       -0.133333             0.0             0.0       -0.142857   
3       -0.133333             0.0             0.0       -0.142857   
4       -0.133333             0.0             0.0       -0.142857   

   rf_bulgeScaled  
0       -0.090909  
1       -0.090909  
2       -0.090909  
3       -0.090909  
4       -0.090909  

[5 rows x 31 columns]

In [5]:
# Converting all the categorical variables to dummy variables
nypdCat = pd.get_dummies(nypdData[['pct','sex','race']])

In [6]:
# Seperating the numerical data
nypdNum = nypdData[['stoppedScaled','arrestedScaled','friskedScaled','searchedScaled','summonedScaled','contrabnScaled','weapnfndScaled','pf_weapnScaled','pf_hcuffScaled','cs_objcsScaled','cs_descrScaled','cs_casngScaled','cs_lkoutScaled','cs_clothScaled','cs_drgtrScaled','cs_furtvScaled','cs_vcrimScaled','cs_bulgeScaled','rf_othswScaled','rf_attirScaled','rf_vcactScaled','rf_rfcmpScaled','rf_verblScaled','rf_knowlScaled','rf_furtvScaled','rf_bulgeScaled']]
nypdNum.shape

(12012, 26)

In [7]:
# Merging with the original data frame
# Preparing the X variables
X = pd.concat([nypdCat, nypdNum], axis=1)
print(X.shape)
# Preparing the Y variable - this is what we will be predicting
# Choose one of the categorical variables
Y = nypdData['race']
print(Y.shape)
X.head()

(12012, 35)
(12012,)


pct  sex_F  sex_M  race_A  race_B  race_I  race_P  race_Q  race_W  \
0  1.0      1      0       1       0       0       0       0       0   
1  1.0      1      0       0       1       0       0       0       0   
2  1.0      1      0       0       0       1       0       0       0   
3  1.0      1      0       0       0       0       1       0       0   
4  1.0      1      0       0       0       0       0       1       0   

   stoppedScaled  ...  cs_vcrimScaled  cs_bulgeScaled  rf_othswScaled  \
0      -0.189573  ...       -0.153846       -0.090909       -0.066667   
1      -0.142180  ...       -0.153846       -0.090909        0.000000   
2      -0.194313  ...       -0.153846       -0.090909       -0.133333   
3      -0.189573  ...       -0.153846       -0.090909       -0.133333   
4      -0.165877  ...       -0.153846       -0.090909       -0.133333   

   rf_attirScaled  rf_vcactScaled  rf_rfcmpScaled  rf_verblScaled  \
0            -0.1       -0.083333       -0.133333             0.0   
1            -0.1       -0.083333       -0.133333             0.0   
2            -0.1       -0.083333       -0.133333             0.0   
3            -0.1       -0.083333       -0.133333             0.0   
4             0.0       -0.083333       -0.133333             0.0   

   rf_knowlScaled  rf_furtvScaled  rf_bulgeScaled  
0             0.0       -0.142857       -0.090909  
1             0.0       -0.142857       -0.090909  
2             0.0       -0.142857       -0.090909  
3             0.0       -0.142857       -0.090909  
4             0.0       -0.142857       -0.090909  

[5 rows x 35 columns]

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=123)
# Defining the LogisticRegression function
nypdModel = LogisticRegression()
nypdModel.fit(X_train, y_train)

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [9]:
pred = nypdModel.predict(X_test)
print('Accuracy of Logistic regression model prediction on test set: {:.2f}'.format(nypdModel.score(X_test, y_test)))

# Confusion Matrix for the model
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

Accuracy of Logistic regression model prediction on test set: 0.97
[[610   2   0   0   3   0]
 [  0 584   3   0  13   5]
 [ 15   0 578   0   1   2]
 [  0   4   0 571   5   3]
 [  3  11   8   2 560   5]
 [  1   4   0   2  12 597]]
              precision    recall  f1-score   support

           A       0.97      0.99      0.98       615
           B       0.97      0.97      0.97       605
           I       0.98      0.97      0.98       596
           P       0.99      0.98      0.99       583
           Q       0.94      0.95      0.95       589
           W       0.98      0.97      0.97       616

    accuracy                           0.97      3604
   macro avg       0.97      0.97      0.97      3604
weighted avg       0.97      0.97      0.97      3604



In [ ]:
print('Percentage of positive class :',(y_train[y_train=='yes'].value_counts()/len(y_train) ) * 100)
print('Percentage of negative class :',(y_train[y_train=='no'].value_counts()/len(y_train) ) * 100)

In [ ]:
# Compare Algorithms
from sklearn.metrics import roc_auc_score
from time import time
from sklearn.metrics import explained_variance_score,mean_absolute_error,r2_score
from pandas import read_csv
from matplotlib import pyplot
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
models = []
models.append(('LR', LogisticRegression(solver='liblinear')))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC(gamma='auto')))
# evaluate each model in turn
results = []
names = []
scoring = 'accuracy'
for name, model in models:
    start = time()
    kfold = KFold(n_splits=10, random_state=7, shuffle=True)
    model.fit(X_train, y_train)
    train_time = time() - start
    cv_results = cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)
    predict_time = time()-start 
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    #y_pred = model.predict_proba(X_train)[:, 1]
    #auc = roc_auc_score(y_train, y_pred)
    print(msg)
    print("Score for each of the 10 K-fold tests: ",cv_results)
    print(model)
    print("\tTraining time: %0.3fs" % train_time)
    print("\tPrediction time: %0.3fs" % predict_time)
    #y_pred = model.predict(X_test)
    #print("\tExplained variance:", explained_variance_score(y_test, y_pred))
    print()
    
    
    
# boxplot algorithm comparison
fig = pyplot.figure()
fig.suptitle('Algorithm Comparison')
ax = fig.add_subplot(111)
pyplot.boxplot(results)
ax.set_xticklabels(names)
pyplot.show()

**Undersampling Method.**

In the random undersampling method, we down sample the majority class to the same amount as the minority class to make the data set balanced. Let us see how we can achieve that

In this method we first identify the count of  the  minority cases and then undersample the majority cases to be the same as minority cases. 




In [ ]:
from sklearn.model_selection import train_test_split

# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=123)


In [ ]:
# let us first join the train_x and train_y for ease of operation

trainData = pd.concat([X_train,y_train],axis=1)
trainData.head()

In [ ]:
# Finding the indexes of the sample data set where the propensity is 'yes'
ind = trainData[trainData['y']=='yes'].index
print(len(ind))

# Seperate the minority classes
minData = trainData.loc[ind]
print(minData.shape)

# Finding indexes of majority class
ind1 = trainData[trainData['y']=='no'].index
print(len(ind1))
# Seperating the majority class
majData = trainData.loc[ind1]
print(majData.shape)
majData.head()

In [ ]:
# Take a random sample equal to length of the minority class to make the data set balanced

majSample = majData.sample(n=len(ind),random_state = 123)
print(majSample.shape)
majSample.head()



In [ ]:
# Concatinating both data sets and then shuffling the data set

balData = pd.concat([minData,majSample],axis = 0)
print('balanced data set shape',balData.shape)

# Shuffling the data set

from sklearn.utils import shuffle

balData = shuffle(balData)
balData.head()

In [ ]:
# Making the new X_train and y_train

X_trainNew = balData.iloc[:,0:51]
X_trainNew.head()

y_trainNew = balData['y']
y_trainNew.head()

In [ ]:

# Defining the LogisticRegression function
bankModel1 = LogisticRegression()
bankModel1.fit(X_trainNew, y_trainNew)

# Predicting on the test
pred = bankModel1.predict(X_test)
print('Accuracy of Logisticr regression model prediction on test set for balanced data set: {:.2f}'.format(bankModel1.score(X_test, y_test)))



In [ ]:
# Confusion Matrix for the model
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

In [ ]:
# Confusion Matrix for the model
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

**Random Over Sampling**

Let us now try the over sampling method and find what effect it has on the results

In [ ]:
!pip install smote-variants

In [ ]:
# Splitting the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

print("Before OverSampling count of yes: {}".format(sum(y_train=='yes')))
print("Before OverSampling count of no: {} \n".format(sum(y_train=='no')))

In [ ]:
import smote_variants as sv
import numpy as np

# Instantiating the SMOTE class
oversampler= sv.SMOTE()

# Creating new training set

X_train_us, y_train_us = oversampler.sample(np.array(X_train), np.array(y_train))

# Shape after oversampling

print('After OverSampling, the shape of train_X: {}'.format(X_train_us.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_us.shape))

print("After OverSampling, counts of label 'Yes': {}".format(sum(y_train_us=='yes')))
print("After OverSampling, counts of label 'no': {}".format(sum(y_train_us=='no')))


In [ ]:
# Training the model with Logistic regression model

# Defining the LogisticRegression function

bankModel2 = LogisticRegression()

bankModel2.fit(X_train_us, y_train_us)

# Predicting on the test set
pred = bankModel2.predict(X_test)

# Printing accuracy 
print('Accuracy of Logistic regression model prediction on test set for Smote balanced data set: {:.2f}'.format(bankModel2.score(X_test, y_test)))

# Confusion Matrix for the model

from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

# Classification report for the model

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))



**Activity 1**

Implementing MSMOTE

In [ ]:
# Splitting the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

print("Before OverSampling count of yes: {}".format(sum(y_train=='yes')))
print("Before OverSampling count of no: {} \n".format(sum(y_train=='no')))

In [ ]:
import smote_variants as sv
import numpy as np
# Instantiating the SMOTE class
oversampler= sv.MSMOTE()
# Creating new training sts
X_train_us, y_train_us = oversampler.sample(np.array(X_train), np.array(y_train))

# Shape after oversampling
print('After OverSampling, the shape of train_X: {}'.format(X_train_us.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_us.shape))

print("After OverSampling, counts of label 'Yes': {}".format(sum(y_train_us=='yes')))
print("After OverSampling, counts of label 'no': {}".format(sum(y_train_us=='no')))

In [ ]:
# Fitting model

# Training the model with Logistic regression model

# Defining the LogisticRegression function
bankModel2 = LogisticRegression()
bankModel2.fit(X_train_us, y_train_us)

# Predicting on the test
pred = bankModel2.predict(X_test)
print('Accuracy of Logistic regression model prediction on test set for Smote balanced data set: {:.2f}'.format(bankModel2.score(X_test, y_test)))

# Confusion Matrix for the model
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))